### ISSUE TITLE
allsets DAN.txt multiple incorrect subtype values

### ISSUE THREAD

**Issue by ChrisMoExp** [SWTCG/SWTCG-LACKEY#16]
multiple cards with the MIssion card type split into the subtype column, against convention
107,
130,
Days Of Fear (Promo),
Nights of Anger (Promo),
91

**Comment by haec0007** [comment]
Isn't that way correct, since, for example, a card's type would be "Mission" and its subtype would be "Campaign" or "Trap"? I'd argue that the cards with a type like "Mission - Trap" are the ones to be changed. Whatever we decide, it should obviously be consistent across the board.

**Comment by ChrisMoExp** [comment]
I can see your thinking. I think there's a counter argument to this that goes along the lines of "mission - campaign" being a very different type of card to a normal mission card.

**Comment by MatthewLarson** [comment]
I've gone back and forth on this same issue on the Cantina... I'm pretty sure I started off making campaign and trap a subtype, but then went back to making it all part of the type because I was worried it would make it harder for people to find the cards they were looking for.

I personally wish that they were just called Campaign or Trap cards, and not Mission - Campaign or Mission - Trap card. I think that would have been less confusing.

**Comment by Matt-Ferus** [comment]
Yeah, officially it's a subtype as the cards are still Mission cards, but just a Trap or Campaign variant. (Like Skills and Traits are subtypes for Equipment).

As for inconsistency, that's likely a result of the Lackey being updated by different crews for different sets at different times.

**Comment by ChrisMoExp** [comment]
subset of #88 which is fixed.
